workers_dev = true
name = "orcamentoauto-site"
compatibility_date = "2024-11-18"
compatibility_flags = [ "nodejs_compat" ]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }
routes = [
  { pattern = "orcamentoauto.com.br", custom_domain = true }
]

